version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: "/bin/true"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: "/bin/true"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10.3
    volumes:
      - ./migrations/V1__Apartments_Table.sql:/docker-entrypoint-initdb.d/V1__Apartments_Table.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flat_box