version: "2"
services:
  api:
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flat_box
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:10.3
    volumes:
      - ./migrations/V1__Apartments_Table.sql:/docker-entrypoint-initdb.d/V1__Apartments_Table.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flat_box