version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
#    volumes:
#      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
